# Temas disponibles
CURRENT_THEME = "dark"  # Cambiar a: "light", "dark", "oled"

# ============ TEMA LIGHT (CLARO) ============
LIGHT = {
    "BG_PRIMARY": "#f5f5f5",
    "BG_SECONDARY": "#ececec",
    "BG_SIDEBAR": "#e8e8e8",
    "BG_CARD": "#ffffff",
    "BG_CARD_HOVER": "#f0f0f0",
    "BG_INPUT": "#ffffff",
    "BG_BORDER": "#d0d0d0",
    
    "TEXT_PRIMARY": "#1a1a1a",
    "TEXT_SECONDARY": "#4a4a4a",
    "TEXT_MUTED": "#808080",
    "TEXT_LINK": "#1976d2",
    
    "ACCENT_MAIN": "#1976d2",
    "ACCENT_HOVER": "#1565c0",
    "ACCENT_SUCCESS": "#388e3c",
    "ACCENT_ERROR": "#d32f2f",
    "ACCENT_WARN": "#f57c00",
}

# ============ TEMA DARK (GRIS OSCURO) ============
DARK = {
    "BG_PRIMARY": "#1e1e1e",
    "BG_SECONDARY": "#2d2d2d",
    "BG_SIDEBAR": "#252525",
    "BG_CARD": "#2a2a2a",
    "BG_CARD_HOVER": "#333333",
    "BG_INPUT": "#1f1f1f",
    "BG_BORDER": "#3a3a3a",
    
    "TEXT_PRIMARY": "#e0e0e0",
    "TEXT_SECONDARY": "#b0b0b0",
    "TEXT_MUTED": "#808080",
    "TEXT_LINK": "#64b5f6",
    
    "ACCENT_MAIN": "#64b5f6",
    "ACCENT_HOVER": "#42a5f5",
    "ACCENT_SUCCESS": "#4caf50",
    "ACCENT_ERROR": "#ef5350",
    "ACCENT_WARN": "#ffb74d",
}

# ============ TEMA OLED (NEGRO PURO) ============
OLED = {
    "BG_PRIMARY": "#000000",
    "BG_SECONDARY": "#0a0a0a",
    "BG_SIDEBAR": "#050505",
    "BG_CARD": "#0f0f0f",
    "BG_CARD_HOVER": "#1a1a1a",
    "BG_INPUT": "#000000",
    "BG_BORDER": "#252525",
    
    "TEXT_PRIMARY": "#ffffff",
    "TEXT_SECONDARY": "#c0c0c0",
    "TEXT_MUTED": "#808080",
    "TEXT_LINK": "#64b5f6",
    
    "ACCENT_MAIN": "#64b5f6",
    "ACCENT_HOVER": "#42a5f5",
    "ACCENT_SUCCESS": "#4caf50",
    "ACCENT_ERROR": "#ef5350",
    "ACCENT_WARN": "#ffb74d",
}

# Seleccionar tema actual
THEMES_DICT = {
    "light": LIGHT,
    "dark": DARK,
    "oled": OLED,
}

ACTIVE_THEME = THEMES_DICT[CURRENT_THEME]

# Exportar colores del tema activo
BG_PRIMARY = ACTIVE_THEME["BG_PRIMARY"]
BG_SECONDARY = ACTIVE_THEME["BG_SECONDARY"]
BG_SIDEBAR = ACTIVE_THEME["BG_SIDEBAR"]
BG_CARD = ACTIVE_THEME["BG_CARD"]
BG_CARD_HOVER = ACTIVE_THEME["BG_CARD_HOVER"]
BG_INPUT = ACTIVE_THEME["BG_INPUT"]
BG_BORDER = ACTIVE_THEME["BG_BORDER"]

TEXT_PRIMARY = ACTIVE_THEME["TEXT_PRIMARY"]
TEXT_SECONDARY = ACTIVE_THEME["TEXT_SECONDARY"]
TEXT_MUTED = ACTIVE_THEME["TEXT_MUTED"]
TEXT_LINK = ACTIVE_THEME["TEXT_LINK"]

ACCENT_MAIN = ACTIVE_THEME["ACCENT_MAIN"]
ACCENT_HOVER = ACTIVE_THEME["ACCENT_HOVER"]
ACCENT_SUCCESS = ACTIVE_THEME["ACCENT_SUCCESS"]
ACCENT_ERROR = ACTIVE_THEME["ACCENT_ERROR"]
ACCENT_WARN = ACTIVE_THEME["ACCENT_WARN"]

# Logging
LOG_ERROR = ACCENT_ERROR
LOG_WARN = ACCENT_WARN
LOG_INFO = ACCENT_MAIN
LOG_DEBUG = TEXT_MUTED
LOG_SUCCESS = ACCENT_SUCCESS

def set_theme(theme_name):
    global CURRENT_THEME, ACTIVE_THEME
    global BG_PRIMARY, BG_SECONDARY, BG_SIDEBAR, BG_CARD, BG_CARD_HOVER
    global BG_INPUT, BG_BORDER, TEXT_PRIMARY, TEXT_SECONDARY, TEXT_MUTED, TEXT_LINK
    global ACCENT_MAIN, ACCENT_HOVER, ACCENT_SUCCESS, ACCENT_ERROR, ACCENT_WARN
    
    if theme_name in THEMES_DICT:
        CURRENT_THEME = theme_name
        ACTIVE_THEME = THEMES_DICT[theme_name]
        
        BG_PRIMARY = ACTIVE_THEME["BG_PRIMARY"]
        BG_SECONDARY = ACTIVE_THEME["BG_SECONDARY"]
        BG_SIDEBAR = ACTIVE_THEME["BG_SIDEBAR"]
        BG_CARD = ACTIVE_THEME["BG_CARD"]
        BG_CARD_HOVER = ACTIVE_THEME["BG_CARD_HOVER"]
        BG_INPUT = ACTIVE_THEME["BG_INPUT"]
        BG_BORDER = ACTIVE_THEME["BG_BORDER"]
        
        TEXT_PRIMARY = ACTIVE_THEME["TEXT_PRIMARY"]
        TEXT_SECONDARY = ACTIVE_THEME["TEXT_SECONDARY"]
        TEXT_MUTED = ACTIVE_THEME["TEXT_MUTED"]
        TEXT_LINK = ACTIVE_THEME["TEXT_LINK"]
        
        ACCENT_MAIN = ACTIVE_THEME["ACCENT_MAIN"]
        ACCENT_HOVER = ACTIVE_THEME["ACCENT_HOVER"]
        ACCENT_SUCCESS = ACTIVE_THEME["ACCENT_SUCCESS"]
        ACCENT_ERROR = ACTIVE_THEME["ACCENT_ERROR"]
        ACCENT_WARN = ACTIVE_THEME["ACCENT_WARN"]
